name: Reusable Workflow
on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    call-reusable-workflow:
  uses: ./.github/workflows/reusable-workflow.yml
  with:
    node: 14
         
  
